### ISSUE TITLE
Async problems with doing event.kill()

### ISSUE THREAD

**Issue by kevinv92** [arjunmehta/heartbeats#11]
event.kill() instantly kills the event but produces async problems if killed before certain code such as https://github.com/arjunmehta/heartbeats/blob/master/lib/heart.js#L161 executes, which is part of heartbeats code. When killed before this line executes `done` would be undefined.

**Where found**
I needed a heart event that runs forever until it meets a condition, in my case, I just do an event.kill() if condition is met. But then, I encountered the issue described.

**(my) Workaround**
Gracefully let the heart kill the event for you by setting `event.done = true`, which is not API, but I think should be. Or something cleaner, like adding a parameter to the createEvent for the exit condition? 

Version: in heartbeats 5.0.1

**Comment by arjunmehta** [comment]
@kevinv92 Thank you for this.

I'm not sure I fully understand what you mean by "async problems".

Please let me confirm that I understand the behavior you want/expect:
You have an ongoing event, but want to essentially queue it up to be killed on its next execution?
I think that is essentially what you're doing when you mark it as `done`, yeah?

Currently, by killing an event, you remove it from the event list and the heart will never iterate over it again.

Something you could do, is have a local variable that is executes `event.kill()` in the event itself.
```javascript
heart.createEvent(1, {name: 'beep'}, function(count, last) {
  console.log('...Every Single Beat forever');
  
  if (conditionIsMet) {
    heart.killEvent('beep');
  }
});
```

**Comment by kevinv92** [comment]
Basically problems with simultaneous code execution, because of handling timed function calls. 

Thanks for the immediate reply!

You've described my problem accurately. 

I did a similar approach with arrow functions and that didn't work, because arrow functions are different I just now remembered . I re-explored this solution but with just simple anonymous functions and it worked! I just wrote a high order function to maintain references to specific variables I needed.

```javascript
const highOrderFunction = function(...vars I need reference in the function) {
 return function() {
  // Do stuff with vars
  if (condition is met) {
   this.kill();
  }
 }
}

heart.createEvent(1, highOrderFunction(..pass in vars));
```

Could you provide yours solution as part of documentation?

**Comment by arjunmehta** [comment]
@kevinv92 great! Yeah arrow functions are nice for that reason (maintaining `this` from the larger scope, but that's not always what a person wants.

Glad it worked for you.

Great idea about adding it to the docs. I'll try to do that soon.

Thanks!

**Comment by arjunmehta** [comment]
@kevinv92 Added the example to the readme: https://github.com/arjunmehta/heartbeats/commit/f8467bbfa1afa4f580679a1c2face5f471d4e664
