### ISSUE TITLE
Compensate very small delay?

### ISSUE THREAD

**Issue by SharpBCD** [arjunmehta/heartbeats#13]
Hi, 
Absolutely excellent module. I'm using it in Node.js in a worker environment to fetch data from an API at every second and I need super precision because if I read 2 times in a sec I get a ban for a couple of minutes. Also losing one second is not ok as we are speaking about financial data stats.
I played with setInterval at 1000 but I lose about 1 milisecond / sec therefore soon it goes to 1 sec.
Heartbeat performed better with the same code, but still there is some delays. I made a workaround and every 10 sec I change the Heart rate from 1000 to 990 and back again after 1 iteration. That compensate some and I may get it to stable rhythm with trial and error but it's just a workaround.

I was wondering if there is any better way to implement a compensation?

Note: `pulse.lag` is returning me the milliseconds since the hart was started. Is this correct?

**Comment by arjunmehta** [comment]
@SharpBCD Thank you for your message.

Unfortunately there is not we can do here. This module actually uses `setInterval` behind the scenes but only uses one.

I'm surprised you're getting better results with the module than with a regular `setInterval`. Unfortunately there will always be a drift when using `setInterval`.

Maybe you want to look into something like the [accurate-interval](https://www.npmjs.com/package/accurate-interval) package?

**Comment by SharpBCD** [comment]
I see. Strange that I got better results.
Your suggestion works perfect. Thank you.
