### ISSUE TITLE
the second time is called, the object created more than one.

### ISSUE THREAD

**Issue by saveroo** [arjunmehta/heartbeats#14]
so i made a discord bot, with discord-js.commando and commander.js as argument parser..

the command looks like this 
`!notif [command] [options]`

so in example if i 
`!notif add food`
it will create a heart with the name of the user who invoke that command, and create an event with random number on the end of name (food_123) 

the first time i invoke it will tell user "Food_123 added"

the first time it is called, it is work just fine, but the second time i call it,  it will create 2 events instead of SUPPOSED only 1; 

the second time will output like this 
"Food_11 added"
"Food_13 added"

so when i check with !notif list it will show that i have 3 events... instead of 2.

i already put a some kind of guard clause above **CREATEEVENT**, just to be sure if heart with that name is exist 
```js
if (!heartbeats.heart(author.username)) {
            this.heart = heartbeats.createHeart(2000, author.username);
            msg.reply(`${this.heart.name} is created`);
 }
```

the question to this problem, should i create a child process for every user that invoke those so they have isolated space on their own ? or which way are the best ?... please light me up.

**Comment by arjunmehta** [comment]
@saveroo Could you please provide more insight into your code?
Not sure how your "Events" are defined... are you using `heart.createEvent`?

**Comment by saveroo** [comment]
i figured it out, the problem lies in commander.js .action method chaining, not the heartbeats,
