### ISSUE TITLE
Can't map heartbeats.hearts?

### ISSUE THREAD

**Issue by danielmariz** [arjunmehta/heartbeats#4]
Are hearts created as object properly?

I can't do this:
`heartbeats.hearts.map( heart => heart.kill() )` 

So I have to do: 
`Object.keys(heartbeats.hearts).forEach( heartName => hearts[heartName].kill() )`

This look weird!

Is there an explanation for it?

**Comment by danielmariz** [comment]
hearts is an object not array.

**Comment by arjunmehta** [comment]
Yes exactly. `hearts` is an object.
Sorry it makes your code look weird :D
