### ISSUE TITLE
Module Exports breaking on browsers

### ISSUE THREAD

**Issue by AStoker** [arjunmehta/heartbeats#8]
Is there a reason why you are calling:  
```
exports = module.exports = SomeObject
```
[like here](https://github.com/arjunmehta/heartbeats/blob/master/lib/pulse.js#L39), instead of calling:
```
module.exports = exports = SomeObject
```
[like here in the main](https://github.com/arjunmehta/heartbeats/blob/master/main.js#L23).
Browsers seem to have trouble interpreting the first syntax correctly when things are bundled together.  
I can make another quick PR to fix it, but wanted to see if there was a specific reason (other than, "It's just how it was written" which is typically my excuse).

**Comment by arjunmehta** [comment]
@AStoker no reason. Definitely feel free to make a PR. Are you using webpack and/or browserify? I've never had this issue before.

**Comment by arjunmehta** [comment]
@AStoker in fact I may remove exports entirely in favour of only using module.exports.

**Comment by arjunmehta** [comment]
Commit https://github.com/arjunmehta/heartbeats/commit/69b2a1cc801f746842bd0842e08a8e45427d54da should fix this.

**Comment by AStoker** [comment]
:) Awesome, thanks. I'm using the Aurelia, which runs RequireJS as a module loader. Someone else is actually having the problem, but I'm helping them out trying to get this library working for them.
